#include "isa/x64.hpp"
#include "linear/registers.hpp"

// x86-64 platform information
// Note this targets System V AMD 64 ABI, not Win64
// Caller-saved: rax, rcx, rdx, rsi, rdi, r8–r11, xmm0–xmm15
// Callee-saved: rbx, rbp, r12–r15
// rsp / rbp register entries: is_protected (not for general allocation) but are for stack and frame pointers

michaelcc::platform_info michaelcc::isa::x64::platform_info{
    .pointer_size   = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64,
    .short_size     = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT16,
    .int_size       = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT32,
    .long_size      = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT32,
    .long_long_size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64,
    .float_size     = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT32,
    .double_size    = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64,
    .max_alignment  = 16,

    .return_register_int8_id   = 3,   // al
    .return_register_int16_id  = 2,   // ax
    .return_register_int32_id  = 1,   // eax
    .return_register_int64_id  = 0,   // rax
    .return_register_float32_id = 68, // xmm0
    .return_register_float64_id = 68, // xmm0

    .stack_pointer_register_id = 32,  // rsp
    .frame_pointer_register_id = 28,  // rbp

    .registers = {
        // rax family for integers
        { .id = 0,  .name = "rax", .description = "RAX",
          .mutually_exclusive_registers = {1, 2, 3, 4},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 1,  .name = "eax", .description = "EAX",
          .mutually_exclusive_registers = {0, 2, 3, 4},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT32, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 2,  .name = "ax",  .description = "AX",
          .mutually_exclusive_registers = {0, 1, 3, 4},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT16, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 3,  .name = "al",  .description = "AL",
          .mutually_exclusive_registers = {0, 1, 2},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_BYTE,   .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 4,  .name = "ah",  .description = "AH",
          .mutually_exclusive_registers = {0, 1, 2},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_BYTE,   .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },

        // rbx family for integers
        { .id = 5,  .name = "rbx", .description = "RBX",
          .mutually_exclusive_registers = {6, 7, 8, 9},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = false, .is_callee_saved = true, .is_protected = false },
        { .id = 6,  .name = "ebx", .description = "EBX",
          .mutually_exclusive_registers = {5, 7, 8, 9},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT32, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = false, .is_callee_saved = true, .is_protected = false },
        { .id = 7,  .name = "bx",  .description = "BX",
          .mutually_exclusive_registers = {5, 6, 8, 9},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT16, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = false, .is_callee_saved = true, .is_protected = false },
        { .id = 8,  .name = "bl",  .description = "BL",
          .mutually_exclusive_registers = {5, 6, 7},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_BYTE,   .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = false, .is_callee_saved = true, .is_protected = false },
        { .id = 9,  .name = "bh",  .description = "BH",
          .mutually_exclusive_registers = {5, 6, 7},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_BYTE,   .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = false, .is_callee_saved = true, .is_protected = false },

        // rcx family for integers
        { .id = 10, .name = "rcx", .description = "RCX",
          .mutually_exclusive_registers = {11, 12, 13, 14},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 11, .name = "ecx", .description = "ECX",
          .mutually_exclusive_registers = {10, 12, 13, 14},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT32, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 12, .name = "cx",  .description = "CX",
          .mutually_exclusive_registers = {10, 11, 13, 14},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT16, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 13, .name = "cl",  .description = "CL",
          .mutually_exclusive_registers = {10, 11, 12},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_BYTE,   .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 14, .name = "ch",  .description = "CH",
          .mutually_exclusive_registers = {10, 11, 12},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_BYTE,   .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },

        // rdx family for integers
        { .id = 15, .name = "rdx", .description = "RDX",
          .mutually_exclusive_registers = {16, 17, 18, 19},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 16, .name = "edx", .description = "EDX",
          .mutually_exclusive_registers = {15, 17, 18, 19},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT32, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 17, .name = "dx",  .description = "DX",
          .mutually_exclusive_registers = {15, 16, 18, 19},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT16, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 18, .name = "dl",  .description = "DL",
          .mutually_exclusive_registers = {15, 16, 17},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_BYTE,   .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 19, .name = "dh",  .description = "DH",
          .mutually_exclusive_registers = {15, 16, 17},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_BYTE,   .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },

        // rsi family for integers
        { .id = 20, .name = "rsi", .description = "RSI",
          .mutually_exclusive_registers = {21, 22, 23},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 21, .name = "esi", .description = "ESI",
          .mutually_exclusive_registers = {20, 22, 23},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT32, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 22, .name = "si",  .description = "SI",
          .mutually_exclusive_registers = {20, 21, 23},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT16, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 23, .name = "sil", .description = "SIL",
          .mutually_exclusive_registers = {20, 21, 22},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_BYTE,   .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },

        // rdi family for integers
        { .id = 24, .name = "rdi", .description = "RDI",
          .mutually_exclusive_registers = {25, 26, 27},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 25, .name = "edi", .description = "EDI",
          .mutually_exclusive_registers = {24, 26, 27},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT32, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 26, .name = "di",  .description = "DI",
          .mutually_exclusive_registers = {24, 25, 27},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT16, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 27, .name = "dil", .description = "DIL",
          .mutually_exclusive_registers = {24, 25, 26},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_BYTE,   .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },

        // rbp family for frame pointer
        { .id = 28, .name = "rbp", .description = "RBP",
          .mutually_exclusive_registers = {29, 30, 31},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = false, .is_callee_saved = true, .is_protected = true },
        { .id = 29, .name = "ebp", .description = "EBP",
          .mutually_exclusive_registers = {28, 30, 31},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT32, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = false, .is_callee_saved = true, .is_protected = true },
        { .id = 30, .name = "bp",  .description = "BP",
          .mutually_exclusive_registers = {28, 29, 31},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT16, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = false, .is_callee_saved = true, .is_protected = true },
        { .id = 31, .name = "bpl", .description = "BPL",
          .mutually_exclusive_registers = {28, 29, 30},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_BYTE,   .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = false, .is_callee_saved = true, .is_protected = true },

        // rsp family for stack pointer
        { .id = 32, .name = "rsp", .description = "RSP",
          .mutually_exclusive_registers = {33, 34, 35},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = false, .is_callee_saved = false, .is_protected = true },
        { .id = 33, .name = "esp", .description = "ESP",
          .mutually_exclusive_registers = {32, 34, 35},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT32, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = false, .is_callee_saved = false, .is_protected = true },
        { .id = 34, .name = "sp",  .description = "SP",
          .mutually_exclusive_registers = {32, 33, 35},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT16, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = false, .is_callee_saved = false, .is_protected = true },
        { .id = 35, .name = "spl", .description = "SPL",
          .mutually_exclusive_registers = {32, 33, 34},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_BYTE,   .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = false, .is_callee_saved = false, .is_protected = true },

          // r8 family for integers
        { .id = 36, .name = "r8",   .description = "R8",
          .mutually_exclusive_registers = {37, 38, 39},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 37, .name = "r8d",  .description = "R8D",
          .mutually_exclusive_registers = {36, 38, 39},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT32, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 38, .name = "r8w",  .description = "R8W",
          .mutually_exclusive_registers = {36, 37, 39},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT16, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 39, .name = "r8b",  .description = "R8B",
          .mutually_exclusive_registers = {36, 37, 38},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_BYTE,   .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },

        // r9 family for integers
        { .id = 40, .name = "r9",   .description = "R9",
          .mutually_exclusive_registers = {41, 42, 43},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 41, .name = "r9d",  .description = "R9D",
          .mutually_exclusive_registers = {40, 42, 43},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT32, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 42, .name = "r9w",  .description = "R9W",
          .mutually_exclusive_registers = {40, 41, 43},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT16, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 43, .name = "r9b",  .description = "R9B",
          .mutually_exclusive_registers = {40, 41, 42},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_BYTE,   .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },

        // r10 family for integers
        { .id = 44, .name = "r10",  .description = "R10",
          .mutually_exclusive_registers = {45, 46, 47},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 45, .name = "r10d", .description = "R10D",
          .mutually_exclusive_registers = {44, 46, 47},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT32, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 46, .name = "r10w", .description = "R10W",
          .mutually_exclusive_registers = {44, 45, 47},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT16, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 47, .name = "r10b", .description = "R10B",
          .mutually_exclusive_registers = {44, 45, 46},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_BYTE,   .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },

        // r11 family for integers
        { .id = 48, .name = "r11",  .description = "R11",
          .mutually_exclusive_registers = {49, 50, 51},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 49, .name = "r11d", .description = "R11D",
          .mutually_exclusive_registers = {48, 50, 51},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT32, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 50, .name = "r11w", .description = "R11W",
          .mutually_exclusive_registers = {48, 49, 51},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT16, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 51, .name = "r11b", .description = "R11B",
          .mutually_exclusive_registers = {48, 49, 50},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_BYTE,   .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },

        // r12 family for integers
        { .id = 52, .name = "r12",  .description = "R12",
          .mutually_exclusive_registers = {53, 54, 55},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = false, .is_callee_saved = true, .is_protected = false },
        { .id = 53, .name = "r12d", .description = "R12D",
          .mutually_exclusive_registers = {52, 54, 55},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT32, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = false, .is_callee_saved = true, .is_protected = false },
        { .id = 54, .name = "r12w", .description = "R12W",
          .mutually_exclusive_registers = {52, 53, 55},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT16, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = false, .is_callee_saved = true, .is_protected = false },
        { .id = 55, .name = "r12b", .description = "R12B",
          .mutually_exclusive_registers = {52, 53, 54},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_BYTE,   .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = false, .is_callee_saved = true, .is_protected = false },

        // r13 family for integers
        { .id = 56, .name = "r13",  .description = "R13",
          .mutually_exclusive_registers = {57, 58, 59},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = false, .is_callee_saved = true, .is_protected = false },
        { .id = 57, .name = "r13d", .description = "R13D",
          .mutually_exclusive_registers = {56, 58, 59},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT32, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = false, .is_callee_saved = true, .is_protected = false },
        { .id = 58, .name = "r13w", .description = "R13W",
          .mutually_exclusive_registers = {56, 57, 59},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT16, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = false, .is_callee_saved = true, .is_protected = false },
        { .id = 59, .name = "r13b", .description = "R13B",
          .mutually_exclusive_registers = {56, 57, 58},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_BYTE,   .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = false, .is_callee_saved = true, .is_protected = false },

        // r14 family for integers
        { .id = 60, .name = "r14",  .description = "R14",
          .mutually_exclusive_registers = {61, 62, 63},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = false, .is_callee_saved = true, .is_protected = false },
        { .id = 61, .name = "r14d", .description = "R14D",
          .mutually_exclusive_registers = {60, 62, 63},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT32, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = false, .is_callee_saved = true, .is_protected = false },
        { .id = 62, .name = "r14w", .description = "R14W",
          .mutually_exclusive_registers = {60, 61, 63},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT16, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = false, .is_callee_saved = true, .is_protected = false },
        { .id = 63, .name = "r14b", .description = "R14B",
          .mutually_exclusive_registers = {60, 61, 62},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_BYTE,   .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = false, .is_callee_saved = true, .is_protected = false },

        // r15 family for integers
        { .id = 64, .name = "r15",  .description = "R15",
          .mutually_exclusive_registers = {65, 66, 67},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = false, .is_callee_saved = true, .is_protected = false },
        { .id = 65, .name = "r15d", .description = "R15D",
          .mutually_exclusive_registers = {64, 66, 67},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT32, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = false, .is_callee_saved = true, .is_protected = false },
        { .id = 66, .name = "r15w", .description = "R15W",
          .mutually_exclusive_registers = {64, 65, 67},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT16, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = false, .is_callee_saved = true, .is_protected = false },
        { .id = 67, .name = "r15b", .description = "R15B",
          .mutually_exclusive_registers = {64, 65, 66},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_BYTE,   .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_INTEGER,
          .is_caller_saved = false, .is_callee_saved = true, .is_protected = false },

        // xmm registers for floats
        { .id = 68, .name = "xmm0",  .description = "XMM0",
          .mutually_exclusive_registers = {},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_FLOATING_POINT,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 69, .name = "xmm1",  .description = "XMM1",
          .mutually_exclusive_registers = {},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_FLOATING_POINT,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 70, .name = "xmm2",  .description = "XMM2",
          .mutually_exclusive_registers = {},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_FLOATING_POINT,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 71, .name = "xmm3",  .description = "XMM3",
          .mutually_exclusive_registers = {},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_FLOATING_POINT,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 72, .name = "xmm4",  .description = "XMM4",
          .mutually_exclusive_registers = {},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_FLOATING_POINT,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 73, .name = "xmm5",  .description = "XMM5",
          .mutually_exclusive_registers = {},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_FLOATING_POINT,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 74, .name = "xmm6",  .description = "XMM6",
          .mutually_exclusive_registers = {},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_FLOATING_POINT,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 75, .name = "xmm7",  .description = "XMM7",
          .mutually_exclusive_registers = {},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_FLOATING_POINT,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 76, .name = "xmm8",  .description = "XMM8",
          .mutually_exclusive_registers = {},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_FLOATING_POINT,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 77, .name = "xmm9",  .description = "XMM9",
          .mutually_exclusive_registers = {},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_FLOATING_POINT,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 78, .name = "xmm10", .description = "XMM10",
          .mutually_exclusive_registers = {},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_FLOATING_POINT,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 79, .name = "xmm11", .description = "XMM11",
          .mutually_exclusive_registers = {},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_FLOATING_POINT,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 80, .name = "xmm12", .description = "XMM12",
          .mutually_exclusive_registers = {},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_FLOATING_POINT,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 81, .name = "xmm13", .description = "XMM13",
          .mutually_exclusive_registers = {},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_FLOATING_POINT,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 82, .name = "xmm14", .description = "XMM14",
          .mutually_exclusive_registers = {},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_FLOATING_POINT,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
        { .id = 83, .name = "xmm15", .description = "XMM15",
          .mutually_exclusive_registers = {},
          .size = michaelcc::linear::word_size::MICHAELCC_WORD_SIZE_UINT64, .reg_class = michaelcc::linear::register_class::MICHAELCC_REGISTER_CLASS_FLOATING_POINT,
          .is_caller_saved = true, .is_callee_saved = false, .is_protected = false },
    }
};
